
*The project is looking for a new maintainer. If you are interested then please write in the following issue: https://github.com/unoconv/unoserver-docker/issues/97*

= Unoserver Container Image

Container image for unoserver

== Fork-specific scope

This repository is a fork of `unoconv/unoserver-docker`. Some content below is inherited from upstream and may not fully reflect fork-specific behavior.

In this fork branch `custom`, `Dockerfile` is intentionally kept aligned with upstream to reduce merge friction. Use `Dockerfile.custom` for branch-specific hardened builds.

The fork is designed and validated primarily for `linux/amd64`.

`linux/arm64` support is kept for upstream compatibility and multi-arch publishing continuity.

Workflow verification steps are architecture-aware:

* Build and image scanning run for both `linux/amd64` and `linux/arm64`
* Integration validation with `pytest` runs only on `linux/amd64`

== The environment

This Container image uses Alpine Linux as a base image and provides:

* link:https://www.libreoffice.org/[LibreOffice]
* link:https://github.com/unoconv/unoserver[unoserver]

* Fonts (Alpine packages)
  - font-noto
  - font-noto-cjk
  - font-noto-extra
  - terminus-font
  - ttf-font-awesome
  - ttf-dejavu
  - ttf-freefont
  - ttf-hack
  - ttf-inconsolata
  - ttf-liberation
  - ttf-mononoki 
  - ttf-opensans  

== How to use it

NOTE: The `docker` can normally be replaced with `podman` as well.

=== In interactive mode

Just run:

[source,bash]
----
docker run -it -v <your directory>:/data/ ghcr.io/unoconv/unoserver-docker
----

After you start the container, you can use link:https://github.com/unoconv/unoserver#unoconvert[unoconvert] command to convert documents using LibreOffice.

or to convert directly using unoconvert:

[source,bash]
----
docker run -it -v <your directory>:/data/ ghcr.io/unoconv/unoserver-docker unoconvert /data/document.docx /data/document.pdf
----

Docker maps your directory with /data directory in the container.

You might need to add the option `:z` or `:Z` like `<your directory>:/data/:z` or `<your directory>:/data/:Z` if you are using SELinux. See link:https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label[Docker docs] or link:https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options[Podman docs].


=== In non-interactive (remote) mode

[source,bash]
----
docker run -p 2003:2003 ghcr.io/unoconv/unoserver-docker
----

After you start the container, you can use link:https://github.com/unoconv/unoserver#unoconvert[unoconvert] command to convert documents using LibreOffice.

NOTE: You must use `--host-location` otherwise unoconvert will default to local although running unoserver in a container should be handled as remote.

[source,bash]
----
unoconvert --host-location remote example.docx example.pdf
----
== FAQ

Q. Why do I get an error during when converting is writing/exporting to file?

A. It's very likely that you haven't given the container write permission to the mounted data directory. See: link:https://github.com/unoconv/unoserver-docker/issues/44[Issue #44]

== How to contribute / do it yourself?

=== Requirements

You need the following tools:

* A bash compliant command line
* Docker installed and in your path

=== How to build

[source,bash]
----
docker build .
----
